### ISSUE TITLE
ClientConnectorError: Cannot connect to host discord.com:443 ssl:default

### ISSUE THREAD

**Issue by sqzhang-jeremy** [openai/gpt-discord-bot#20]
Hey guys! I met a connection issue, which disturbed me from using this chatbot.

I am using MacOS Monterey V12.5.1 M1.

The relevant codes are as follows:

(conda) jeremyzhang@Jeremys-MacBook-Pro gpt-discord-bot % python3 -m src.main
2023-01-21 15:05:59 INFO     discord.client logging in using static token
[2023-01-21 15:05:59,106] [client.py:571] logging in using static token
Traceback (most recent call last):
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/base_events.py", line 1073, in create_connection
    raise exceptions[0]
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/base_events.py", line 1058, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/base_events.py", line 964, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/selector_events.py", line 633, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 61] Connect call failed ('4.78.139.54', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jeremyzhang/Desktop/ChatGPT Stuff/gpt-discord-bot/src/main.py", line 267, in <module>
    client.run(DISCORD_BOT_TOKEN)
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/client.py", line 745, in start
    await self.login(token)
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/client.py", line 580, in login
    data = await self.http.static_login(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/http.py", line 801, in static_login
    data = await self.request(Route('GET', '/users/@me'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/discord/http.py", line 624, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeremyzhang/miniforge3/envs/deepwisdom/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('4.78.139.54', 443)]

**Comment by sqzhang-jeremy** [comment]
I got something, but it's hard to tackle it https://www.pythonanywhere.com/forums/topic/7384/#id_post_42150.

**Comment by YufeiG** [comment]
Are you still stuck?

For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757)
