### ISSUE TITLE
Running the bot problem

### ISSUE THREAD

**Issue by Darkvic123** [openai/gpt-discord-bot#33]
When I installed the dependencies, I got an error message like this:

WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\Python311\Scripts\dotenv.exe' -> 'C:\Python311\Scripts\dotenv.exe.deleteme'

Then I tried using the commands separately but it wasnt any better, then, I use --user after the commands and got a different issue:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vboxuser\Documents\gpt-discord-bot-main\src\main.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
PS C:\Users\vboxuser\Documents\gpt-discord-bot-main> python -m src.main --user
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vboxuser\Documents\gpt-discord-bot-main\src\main.py", line 1, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

**Comment by YufeiG** [comment]
I do not run this on windows. Try installing the pip deps the way you do it on windows instead of using the requirements file? So install the discord lib the way people do it on windows.

**Comment by YufeiG** [comment]
For help, please use [Discord API Discussions](https://discord.com/channels/974519864045756446/1037561178286739466) or [Discord Project Post](https://discord.com/channels/974519864045756446/1055336272543092757)
