### ISSUE TITLE
BotMissingPermissions: Bot requires View Channel permission(s) to run this command

### ISSUE THREAD

**Issue by joonas-yoon** [openai/gpt-discord-bot#47]
**Describe the bug**

I am trying to run basic example from this repo. but I got an error as like following:

```
2023-02-17 20:34:24 ERROR    discord.app_commands.tree Ignoring exception in command 'chat'
Traceback (most recent call last):
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\app_commands\tree.py", line 1242, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 883, in _invoke_with_namespace
    if not await self._check_can_run(interaction):
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 1021, in _check_can_run
    return await async_all(f(interaction) for f in predicates)
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\utils.py", line 672, in async_all
    for elem in gen:
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\app_commands\commands.py", line 1021, in <genexpr>
    return await async_all(f(interaction) for f in predicates)
  File "C:\dev\gpt-discord-bot\.venv\lib\site-packages\discord\app_commands\checks.py", line 365, in predicate
    raise BotMissingPermissions(missing)
discord.app_commands.errors.BotMissingPermissions: Bot requires View Channel permission(s) to run this command.
```

I think this is problem about permission on Discord, so I checked and try again but still failed.

Another problem is, generated invite URL is wrong.

In the log when I run, I got the message:

```
[2023-02-17 20:34:20,093] [main.py:42] We have logged in as <mybot>. Invite URL: https://discord.com/api/oauth2/authorize?client_id=...&permissions=328565073920&scope=bot
```

and I can see the number `328565073920` for permission. but it has no permission to view channels according the documentation (https://discord.com/developers/docs/topics/permissions#permissions-bitwise-permission-flags)

|PERMISSION|VALUE|DESCRIPTION|CHANNEL TYPE|
|-|-|-|-|
|VIEW_CHANNEL | `0x0000000000000400` (1 << 10) | Allows guild members to view a channel, which includes reading messages in text channels and joining voice channels | T, V, S |

the result of `328565073920 & (1 << 10)` is `0` that means having no permission `VIEW_CHANNEL` as I know.

**To Reproduce**
1. Run `python -m src.main`
2. Send `/chat` command with any message.

**Expected behavior**

shows invite url `https://discord.com/api/oauth2/authorize?client_id=...&permissions=328565073920&scope=bot`

**What OS are you running this on? (please complete the following information):**
 - Windows 10
 - python 3.10
 - discord.py==2.1.1

**Additional context**

I changed permission but still happends :/

**Comment by ctastad** [comment]
It turns out I missed step 6 in the setup, which resolved this issue.

> Copy the ID the server you want to allow your bot to be used in by right clicking the server icon and clicking "Copy ID". Fill in ALLOWED_SERVER_IDS. If you want to allow multiple servers, separate the IDs by "," like server_id_1,server_id_2
