### ISSUE TITLE
[utils.py:68] Guild XXXXXXX not allowed

### ISSUE THREAD

**Issue by mambas23** [openai/gpt-discord-bot#8]
Hello, I have a small problem, I created the bot with all the necessary information. But when I decide to add the id of the server in question in the untils.py file, I have an error message. Which tells me :

-----
C:\Users\User\Downloads\gpt-discord-bot-main\gpt-discord-bot-main>python -m src.main
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Downloads\gpt-discord-bot-main\gpt-discord-bot-main\src\main.py", line 14, in <module>
    from src.utils import (
  File "C:\Users\User\Downloads\gpt-discord-bot-main\gpt-discord-bot-main\src\utils.py", line 2
    ALLOWED_SERVER_IDS, 813XXXXXXXX
                                          ^
                  SyntaxError: invalid syntax

-----

I don't understand, thank you in advance for your help.

**Comment by YufeiG** [comment]
You want “ ALLOWED_SERVER_IDS=813xxxx”
